title: 進化
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname: gothwski

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
